### ISSUE TITLE
Only half of the picture is generated

### ISSUE THREAD

**Issue by emilfihlman** [makegirlsmoe/makegirlsmoe_web#23] opened 2017-09-17 10:43 UTC
Console shows:
Failed to initialize webgpu backend: Error: WebGPU backend is not supported in this browser.
But half of the image is still generated.

**Comment by Aixile** [comment] 2017-09-17 12:23
Thanks for reporting the issue. 
Previously, we have WebAssembely backend and WebGPU backend. But WebGPU backend can only work on macOS.
Recently, we add WebGL backend to support the general GPU computation on different devices. 
It seems that WebGL backend failed to execute on some PCs. We are trying to figure out the reason, but we are not able to reproduce this bug.

Can you give me following information
1. Which OS are you using?
2. What is your CPU vendor?
2. Do you have an extra graphic card? If so, what is your GPU vendor?

**Comment by emilfihlman** [comment] 2017-09-17 13:07
Thanks for trying to fix it!

1. Windows 10 Pro 64-bit
2. Intel(R) Core(TM) i7-4650U
3. No extra graphics card

Browser I use is Google Chrome 61.0.3163.91 but I got the same result on Firefox.

Here's an example it generates:

![moe](https://user-images.githubusercontent.com/9070088/30521091-07bc1422-9bc2-11e7-9b2b-bcb075858ae8.png)

**Comment by 0w0miki** [comment] 2017-10-23 13:21
Same problem. System configuration is:
OS: Win10 build 1703 64bit
CPU: Intel Core(TM) i5-3230m
GPU: Nvidia GT640m
browser: Nightly 58 and Firefox 55

**Comment by Aixile** [comment] 2017-10-23 13:29
Thanks for the report.
This issue is related to https://github.com/mil-tokyo/webdnn/issues/563.
The integer precision is dependent on the hardware implementation.
Though https://github.com/mil-tokyo/webdnn/issues/563 is fixed,  there still remains some numerical problems in the WebGL calculation in the lastest WebDNN, we have to wait.

**Comment by Aixile** [comment] 2017-11-25 08:42
We made a major update today and the bug should be fixed.

**Closed** 2017-12-19 05:21 UTC
Labels: bug
